apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
spec:
  replicas: 1
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: todo-api 
            optional: false
