apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
spec:
  template:
    spec:
      containers:
      - 
        envFrom:
        - configMapRef:
            name: todo-api 
            optional: false
