apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "exochart.fullname" . }}
spec:
  port:
    targetPort: {{ .Values.service.port | default 8080 }}
  #tls:
  #  termination: passthrough
  to:
    kind: Service
    name: exochart
    weight: 100
